name: test

on:
  push:
    paths:
      - 'llcomNext/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'llcomNext/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: environment prepare
        run: |
          choco install dotnet-7.0-runtime -y
          choco install dotnet-7.0-sdk -y
      - name: test
        run: |
          cd llcomNext
          dotnet test
